### ISSUE TITLE
About Metrics

### ISSUE THREAD

**Issue by bugczw** [li-plus/DSNet#13]
When measuring the model, you use the f1 score and treat the entire video summary task as a sequence labeling task. But in the process of condensing the video, the positive and negative samples are often extremely unbalanced. So does the f1 score really make sense?
In addition, in your code, you use the average method for tvsum data set , but for other data sets use the maximum value. I want to ask the reason for this.

**Comment by li-plus** [comment]
Hi, F1-score can deal with unbalanced data in binary classification tasks, since it is the harmonic mean of precision & recall. High precision prevents the model from predicting all ones, and high recall prevents it from all zeros. F1-score strikes the balance of precision & recall, and it is far better than accuracy.

Following [VASNet](https://github.com/ok1zjf/VASNet), we use average F1-score for TVSum and max F1-score for SumMe for a fair comparison.
