### ISSUE TITLE
summary video can't be played

### ISSUE THREAD

**Issue by hionwi** [li-plus/DSNet#19]
When I use infer.py to predict my own video, the generated summary video cannot be played, but it can be played when predicting the video provided by the author

**Comment by li-plus** [comment]
We do video I/O using OpenCV API. Please check if OpenCV supports your video format.

**Comment by Luizerko** [comment]
I had a problem similar to yours. I think it`s because the automatic KTS algorithm is not always able to find multiple change points. When something like this happens, you will probably have something like [[0 #number_of_frames-1]] as your cps. I fixed it by using the manual KTS instead of the automatic one when len(cps) <= 1. This will make your cps array bigger and then the algorithm can go back to choosing what are the best segments to use in the summary video.

(Check the VideoPreprocessor class on video_helper file. Look for the kts function and try to use cpd_nonlin instead of cpd_auto in the len(cps) <= 1 case).

**Comment by hionwi** [comment]
@Luizerko Thank you for your reply. Would you please show the changed code?

**Comment by Luizerko** [comment]
@hionwi of course!

Maybe try adding
`from kts.cpd_nonlin import cpd_nonlin`

And then
`change_points, _ = cpd_auto(kernel, seq_len - 1, 1, verbose=False)`
`if len(change_points) <= 1:`
    `change_points, _ = cpd_nonlin(kernel, <choose_your_number_of_change_points>, 1, <choose_your_max_number_of_frames_per_segment>, verbose=False)`

**Comment by azadehashouri** [comment]
> @hionwi of course!
> 
> Maybe try adding `from kts.cpd_nonlin import cpd_nonlin`
> 
> And then `change_points, _ = cpd_auto(kernel, seq_len - 1, 1, verbose=False)` `if len(change_points) <= 1:` `change_points, _ = cpd_nonlin(kernel, <choose_your_number_of_change_points>, 1, <choose_your_max_number_of_frames_per_segment>, verbose=False)`

Hi, thank you for sharing this code.
Would you explain about the way of setting "number_of_change_points" and "max_number_of_frames_per_segment"?
Thanks
